dev7a/serverless-otlp-forwarder

otlp-stdout-client/rust/client/Cargo.toml
otlp-stdout-client/rust/client/README.md
otlp-stdout-client/rust/client/src/lambda_detector.rs
otlp-stdout-client/rust/client/src/lib.rs

direclty added aws lambda detector

---

packages/node/exporter/README.md

fix: update deprecated method signature

---

packages/rust/lambda-lw-http-router/router-core/CHANGELOG.md
packages/rust/lambda-lw-http-router/router-core/Cargo.toml
packages/rust/lambda-lw-http-router/router-core/src/routable_http_event.rs

use set_attribute

---

packages/rust/lambda-otel-lite/CHANGELOG.md
packages/rust/lambda-otel-lite/Cargo.toml
packages/rust/lambda-otel-lite/README.md
packages/rust/lambda-otel-lite/examples/Cargo.toml
packages/rust/lambda-otel-lite/examples/README.md
packages/rust/lambda-otel-lite/examples/handler/main.rs
packages/rust/lambda-otel-lite/examples/template.yaml
packages/rust/lambda-otel-lite/examples/tower/main.rs
packages/rust/lambda-otel-lite/src/extension.rs
packages/rust/lambda-otel-lite/src/extractors.rs
packages/rust/lambda-otel-lite/src/handler.rs
packages/rust/lambda-otel-lite/src/layer.rs
packages/rust/lambda-otel-lite/src/lib.rs
packages/rust/lambda-otel-lite/src/processor.rs
packages/rust/lambda-otel-lite/src/resource.rs
packages/rust/lambda-otel-lite/src/telemetry.rs

This pull request introduces several enhancements and new features to the `lambda-otel-lite` project, including new modules, improved documentation, and example Lambda functions demonstrating different instrumentation approaches. The most important changes are grouped by theme:
* Added a new `extractors` module for attribute extraction from Lambda events and a new `resource` module for Lambda resource attribute management.
* Introduced automatic extraction of AWS Lambda resource attributes and better support for custom event types through the `SpanAttributesExtractor` trait.
* Comprehensive documentation for all modules and features, including detailed examples for common use cases and integration patterns.
* Improved architecture documentation with module responsibilities and enhanced …

Feat/rust lol 0.6.0

---

.github/workflows/publish-node-lambda-otel-lite.yml
packages/node/lambda-otel-lite/CHANGELOG.md
packages/node/lambda-otel-lite/README.md
packages/node/lambda-otel-lite/__tests__/fixtures/alb.json
packages/node/lambda-otel-lite/__tests__/fixtures/apigw_v1_proxy.json
packages/node/lambda-otel-lite/__tests__/fixtures/apigw_v2_proxy.json
packages/node/lambda-otel-lite/__tests__/handler.test.ts
packages/node/lambda-otel-lite/__tests__/telemetry/init.test.ts
packages/node/lambda-otel-lite/examples/handler/app.js
packages/node/lambda-otel-lite/examples/template.yaml
packages/node/lambda-otel-lite/package-lock.json
packages/node/lambda-otel-lite/package.json
packages/node/lambda-otel-lite/src/handler.ts
packages/node/lambda-otel-lite/src/internal/telemetry/extractors.ts
packages/node/lambda-otel-lite/src/internal/telemetry/init.ts
packages/node/lambda-otel-lite/tsconfig.json

This pull request includes significant updates to the `lambda-otel-lite` package, including changes to the workflow, breaking changes in the handler function signature, updates to the README, and new test fixtures. Below are the most important changes:
* Added a new GitHub Actions workflow for publishing the Node.js Lambda OTel Lite package. This workflow includes steps for setting up Node.js, installing dependencies, running quality checks, verifying the package, and publishing it to npm. (`.github/workflows/publish-node-lambda-otel-lite.yml`)
* Updated the handler function signature to remove direct span access and changed the handler creation API to match the Python implementation. (`packages/node/lambda-otel-lite/CHANGELOG.md`)
* Updated the README to reflect changes in the handler …

Release/node lambda otel lite 0.8.0 

---

packages/python/lambda_otel_lite/CHANGELOG.md
packages/python/lambda_otel_lite/PUBLISHING.md
packages/python/lambda_otel_lite/pyproject.toml
packages/python/lambda_otel_lite/src/lambda_otel_lite/__init__.py
packages/python/lambda_otel_lite/src/lambda_otel_lite/extension.py
packages/python/lambda_otel_lite/src/lambda_otel_lite/extractors.py
packages/python/lambda_otel_lite/tests/test_extractors.py

This pull request includes several changes to improve the consistency and robustness of attribute extraction in the `lambda_otel_lite` package. Key changes include updates to the changelog, adjustments to the publishing process, version bump, and multiple improvements to the extractor functions.
* **Changelog and Versioning:**
* Updated `CHANGELOG.md` to document the changes in version 0.8.1, including fixes and improvements to API Gateway v2 event extraction and attribute handling.
* Bumped the version in `pyproject.toml` from 0.8.0 to 0.8.1.
* **Publishing Process:**
* Modified `PUBLISHING.md` to update the linting command to use `ruff` with isolated mode for specific directories.
* **Extractor Functions:**
* Introduced `_normalize_headers` function to standardize header names to …

Release/python lambda otel lite 0.8.1

---

packages/rust/otlp-sigv4-client/CHANGELOG.md
packages/rust/otlp-sigv4-client/Cargo.toml
packages/rust/otlp-sigv4-client/PUBLISHING.md
packages/rust/otlp-sigv4-client/README.md
packages/rust/otlp-sigv4-client/examples/sigv4_auth/README.md
packages/rust/otlp-sigv4-client/examples/sigv4_auth/main.rs
packages/rust/otlp-sigv4-client/src/builder.rs
packages/rust/otlp-sigv4-client/src/lib.rs
packages/rust/otlp-sigv4-client/src/signing.rs

This pull request includes several significant changes to the `otlp-sigv4-client` package, focusing on version updates, improved documentation, enhanced error handling, and the addition of a comprehensive test suite. The changes aim to improve the overall functionality, usability, and compatibility of the package.
* [`packages/rust/otlp-sigv4-client/Cargo.toml`](diffhunk://#diff-1e938d753bdb6c89817071afb42989c28fabecd5cd7fb9b71d4a650cb13abb76L3-R3): Updated the package version from `0.3.0` to `0.10.0` and added new feature flags for better dependency management. [[1]](diffhunk://#diff-1e938d753bdb6c89817071afb42989c28fabecd5cd7fb9b71d4a650cb13abb76L3-R3) [[2]](diffhunk://#diff-1e938d753bdb6c89817071afb42989c28fabecd5cd7fb9b71d4a650cb13abb76R33-L41)
* …

Release otlp-sigv4-client v0.10.0

---

packages/rust/lambda-otel-lite/CHANGELOG.md
packages/rust/lambda-otel-lite/Cargo.toml
packages/rust/lambda-otel-lite/PUBLISHING.md
packages/rust/lambda-otel-lite/README.md
packages/rust/lambda-otel-lite/examples/README.md
packages/rust/lambda-otel-lite/examples/handler/main.rs
packages/rust/lambda-otel-lite/src/telemetry.rs

This pull request includes several updates and improvements to the `lambda-otel-lite` package, focusing on bug fixes, documentation enhancements, and dependency updates. The most important changes are summarized below:
* Removed debug `println!` statement from `TelemetryCompletionHandler::complete` method.
* Enhanced `README.md` with more detailed examples and explanations, added a Table of Contents, and improved formatting and structure of code examples.
* Updated `PUBLISHING.md` with correct release branch naming pattern.
* Added `aws_lambda_events` with Kinesis feature and `http` dependencies to `Cargo.toml`.
* Updated `examples/README.md` to include detailed deployment instructions, testing, and cleanup steps.
* Modified `handler/main.rs` to use `ApiGatewayV2httpResponse` for proper …

Release rust-lambda-otel-lite v0.10.1

---

.github/workflows/publish-node-lambda-otel-lite.yml
.github/workflows/publish-node-otlp-stdout-span-exporter.yml
packages/node/lambda-otel-lite/CHANGELOG.md
packages/node/lambda-otel-lite/PUBLISHING.md
packages/node/lambda-otel-lite/README.md
packages/node/lambda-otel-lite/__tests__/test_resource.ts
packages/node/lambda-otel-lite/package-lock.json
packages/node/lambda-otel-lite/package.json
packages/node/lambda-otel-lite/src/constants.ts
packages/node/lambda-otel-lite/src/index.ts
packages/node/lambda-otel-lite/src/internal/telemetry/init.ts
packages/node/lambda-otel-lite/src/internal/telemetry/processor.ts
packages/node/lambda-otel-lite/src/internal/telemetry/resource.ts
packages/node/lambda-otel-lite/src/mode.ts
packages/node/lambda-otel-lite/src/version.ts

This pull request includes multiple changes to the `lambda-otel-lite` package, focusing on improving configuration handling, updating documentation, and enhancing code organization. The most important changes include breaking changes to configuration precedence, updates to the `LambdaSpanProcessor`, and refactoring for better code maintainability.
* **Breaking Change**: Configuration precedence is updated to ensure environment variables always take precedence over constructor parameters. (`packages/node/lambda-otel-lite/CHANGELOG.md`, `packages/node/lambda-otel-lite/README.md`, `packages/node/lambda-otel-lite/src/internal/telemetry/processor.ts`) [[1]](diffhunk://#diff-639c39db47031fa119e62d0d1eb34488b39daf098c3a267200c598fd8989384dR8-R21) …

release node lambda-otel-lite v0.11.0

---

packages/python/lambda-otel-lite/CHANGELOG.md
packages/python/lambda-otel-lite/PUBLISHING.md
packages/python/lambda-otel-lite/examples/template.yaml
packages/python/lambda-otel-lite/pyproject.toml
packages/python/lambda-otel-lite/src/lambda_otel_lite/__init__.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/constants.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/processor.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/resource.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/telemetry.py

This pull request introduces several enhancements and fixes to the `lambda-otel-lite` package, including new modules, improved configuration handling, and better code organization. The most important changes include the addition of a new `constants` module, a dedicated `resource` module, and several updates to improve consistency and error handling.
* Added a new `constants` module to centralize environment variables, defaults, and resource attributes. (`packages/python/lambda-otel-lite/src/lambda_otel_lite/constants.py`)
* Introduced a dedicated `resource` module for resource creation and attribute management. (`packages/python/lambda-otel-lite/src/lambda_otel_lite/resource.py`)
* Improved environment variable precedence, ensuring that environment variables always take precedence over …

release python lambda-otel-lite v0.11.0

---

packages/rust/lambda-otel-lite/CHANGELOG.md
packages/rust/lambda-otel-lite/Cargo.toml
packages/rust/lambda-otel-lite/PUBLISHING.md
packages/rust/lambda-otel-lite/README.md
packages/rust/lambda-otel-lite/docs/xray-propagation.md
packages/rust/lambda-otel-lite/examples/template.yaml
packages/rust/lambda-otel-lite/src/constants.rs
packages/rust/lambda-otel-lite/src/extractors.rs
packages/rust/lambda-otel-lite/src/lib.rs
packages/rust/lambda-otel-lite/src/processor.rs
packages/rust/lambda-otel-lite/src/propagation.rs
packages/rust/lambda-otel-lite/src/resource.rs
packages/rust/lambda-otel-lite/src/telemetry.rs

This pull request introduces significant updates to the `lambda-otel-lite` package, including new features, improvements, and documentation enhancements. The changes focus on adding support for AWS X-Ray propagation, improving configuration handling, and centralizing constants for better consistency.
* **AWS X-Ray Propagation Support**: Added support for AWS X-Ray propagation through the `OTEL_PROPAGATORS` environment variable and introduced the `LambdaXrayPropagator` for enhanced X-Ray propagation with Lambda environment detection. (`README.md`, `xray-propagation.md`, `constants.rs`, `extractors.rs`) [[1]](diffhunk://#diff-1c26ba0d854aa5ea68e0f15ae91f4cad8300defcce057be8cecb5f54be8d612aL335-R354) [[2]](diffhunk://#diff-b473e48459ebbfd1e35e81ea61eff0ca75c0881ea717ae56ce9ffdc862a4ee64R1-R14 …

Release rust lambda otel lite v0.11.0

---

packages/rust/otlp-stdout-client/src/lib.rs

Fix compiler error caused by missing `send_bytes` method impl for `HttpClient`, `send()` defaults to `send_bytes`, but `send_bytes` is a required method.

Fix impl HttpClient for StdoutClient for otlp-stdout-client

---

demo/rust/Cargo.toml
demo/rust/src/backend/main.rs
demo/rust/src/frontend/main.rs

This pull request includes several changes to the `demo/rust` project, focusing on code simplification and cleanup. The main changes involve reformatting the creation of traced handlers in both the backend and frontend `main.rs` files, and a small cleanup in the `Cargo.toml` file.
Code simplification:
* [`demo/rust/src/backend/main.rs`](diffhunk://#diff-97f70091393f94357e840b174f593b069184e3f9c1dc20de1911a447a3a44410L270-R275): Refactored the creation of the `traced_handler` to simplify the code by removing unnecessary line breaks and parentheses.
* [`demo/rust/src/frontend/main.rs`](diffhunk://#diff-92107f0c2ace8f8d8b3dd5752f29eac0c37593599100b51ae3bcedffaae081cbL425-R430): Refactored the creation of the `traced_handler` to simplify the code by removing unnecessary line breaks and …

refactor: improve code formatting in demo directory

---

packages/rust/lambda-otel-lite/CHANGELOG.md
packages/rust/lambda-otel-lite/Cargo.toml
packages/rust/lambda-otel-lite/README.md
packages/rust/lambda-otel-lite/examples/README.md
packages/rust/lambda-otel-lite/src/telemetry.rs

This pull request includes several important changes to the `lambda-otel-lite` package, focusing on improving environment variable handling, adding custom ID generator configuration, and updating documentation. The most significant changes are outlined below:
* Improved handling of the `LAMBDA_TRACING_ENABLE_FMT_LAYER` environment variable to validate "true" or "false" values, added precedence over code configuration, and included warnings for invalid values with fallback to code configuration. [[1]](diffhunk://#diff-186498266ac8e953c6310f423de26221c85a117655d116518dd6abf581d93900R8-R17) [[2]](diffhunk://#diff-12e540601f25150dea6d8f3d1da7dd92b2e7b1c8100696849434ddb1d5ec32f6R572) [[3]](diffhunk://#diff-12e540601f25150dea6d8f3d1da7dd92b2e7b1c8100696849434ddb1d5ec32f6L577-R630) …

release rust lambda-otel-lite v0.11.3

---

packages/python/lambda-otel-lite/CHANGELOG.md
packages/python/lambda-otel-lite/PUBLISHING.md
packages/python/lambda-otel-lite/README.md
packages/python/lambda-otel-lite/examples/template.yaml
packages/python/lambda-otel-lite/pyproject.toml
packages/python/lambda-otel-lite/src/lambda_otel_lite/__init__.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/config.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/constants.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/extractors.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/handler.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/propagation.py
packages/python/lambda-otel-lite/src/lambda_otel_lite/telemetry.py
packages/python/lambda-otel-lite/tests/test_config.py
packages/python/lambda-otel-lite/tests/test_extractors.py
packages/python/lambda-otel-lite/tests/test_processor_mode.py
packages/python/lambda-otel-lite/tests/test_propagation.py
packages/python/otlp-stdout-span-exporter/CHANGELOG.md
packages/python/otlp-stdout-span-exporter/PUBLISHING.md
packages/python/otlp-stdout-span-exporter/README.md
packages/python/otlp-stdout-span-exporter/examples/simple_stdout_hello.py
packages/python/otlp-stdout-span-exporter/pyproject.toml
packages/python/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter/constants.py
packages/python/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter/exporter.py
packages/python/otlp-stdout-span-exporter/tests/test_otlp_stdout_span_exporter.py

This pull request includes several updates to the `lambda-otel-lite` package, focusing on new features, configuration improvements, and code enhancements. The most important changes include adding support for new configuration options, updating the configuration precedence, and improving the codebase for consistency and maintainability.
* Added support for configuring processor mode programmatically via the `processor_mode` parameter in `init_telemetry`, and context propagation via the `OTEL_PROPAGATORS` environment variable. (`packages/python/lambda-otel-lite/CHANGELOG.md`, `packages/python/lambda-otel-lite/README.md`, `packages/python/lambda-otel-lite/src/lambda_otel_lite/constants.py`) [[1]](diffhunk://#diff-0255a9d95a4789e536efd018d471d0d9540ba1e008ff7386e9f648124b36f1e9R8-R21) …

release: python/lambda otel lite v0.13.0

---

packages/node/lambda-otel-lite/CHANGELOG.md
packages/node/lambda-otel-lite/PUBLISHING.md
packages/node/lambda-otel-lite/README.md
packages/node/lambda-otel-lite/__tests__/test_config.ts
packages/node/lambda-otel-lite/__tests__/test_extractors.ts
packages/node/lambda-otel-lite/__tests__/test_handler.ts
packages/node/lambda-otel-lite/__tests__/test_init.ts
packages/node/lambda-otel-lite/__tests__/test_mode.ts
packages/node/lambda-otel-lite/__tests__/test_propagation.ts
packages/node/lambda-otel-lite/__tests__/test_resource.ts
packages/node/lambda-otel-lite/__tests__/utils.ts
packages/node/lambda-otel-lite/examples/handler/app.ts
packages/node/lambda-otel-lite/examples/handler/tsconfig.json
packages/node/lambda-otel-lite/examples/samconfig.example.toml
packages/node/lambda-otel-lite/examples/template.yaml
packages/node/lambda-otel-lite/package-lock.json
packages/node/lambda-otel-lite/package.json
packages/node/lambda-otel-lite/src/constants.ts
packages/node/lambda-otel-lite/src/extension/index.js
packages/node/lambda-otel-lite/src/extractors/index.ts
packages/node/lambda-otel-lite/src/handler.ts
packages/node/lambda-otel-lite/src/index.ts
packages/node/lambda-otel-lite/src/internal/config.ts
packages/node/lambda-otel-lite/src/internal/propagation.ts
packages/node/lambda-otel-lite/src/internal/telemetry/extractors.ts
packages/node/lambda-otel-lite/src/internal/telemetry/init.ts
packages/node/lambda-otel-lite/src/internal/telemetry/processor.ts
packages/node/lambda-otel-lite/src/mode.ts

This pull request introduces significant enhancements to the `@dev7a/lambda-otel-lite` package, including new features, improved type safety, better configuration handling, and expanded test coverage. Below is a summary of the most important changes:
* Added support for configuring processor mode programmatically via the `processorMode` option in `initTelemetry`, with environment variable `LAMBDA_EXTENSION_SPAN_PROCESSOR_MODE` taking precedence.
* Introduced the `OTEL_PROPAGATORS` environment variable for flexible context propagation, supporting values like `tracecontext`, `xray`, `xray-lambda`, and `none`. Defaults updated to use `[LambdaXRayPropagator(), W3CTraceContextPropagator()]` when not explicitly set. [[1]](diffhunk://#diff-639c39db47031fa119e62d0d1eb34488b39daf098c3a267200c598fd8 …

release: node/lambda otel lite v0.13.0

---

cli/startled/Cargo.toml
cli/startled/README.md
cli/startled/src/benchmark.rs
cli/startled/src/console.rs
cli/startled/src/lambda.rs
cli/startled/src/main.rs
cli/startled/src/report.rs
cli/startled/src/stats.rs
cli/startled/src/types.rs

This pull request introduces enhancements to the `startled` CLI tool, focusing on improving benchmarking capabilities, updating dependencies, and enhancing code readability. The changes include updates to dependency configurations, improved statistical reporting in HTML and console outputs, and better error handling and formatting in the codebase.
* Updated `Cargo.toml` to modify dependencies such as `comfy-table`, `regex`, `rust_decimal`, and `pulldown-cmark` to use workspace configurations and enable additional features like "tty" and "custom_styling" for `comfy-table`.
* Enhanced the statistical summaries in the README and console outputs to include standard deviation (StdDev) for metrics like cold start duration, memory usage, and response latency. …

feat: capture additional metrics 

---

cli/startled/CHANGELOG.md
cli/startled/Cargo.toml
cli/startled/LICENSE
cli/startled/PUBLISHING.md
cli/startled/README.md
cli/startled/RELEASE_NOTES.md
cli/startled/src/benchmark.rs
cli/startled/src/main.rs
cli/startled/src/report.rs
cli/startled/src/screenshot.rs
cli/startled/src/stats.rs
cli/startled/src/telemetry.rs
cli/startled/src/templates/chart.html
cli/startled/src/templates/css/style.css
cli/startled/src/templates/index.html
cli/startled/src/templates/js/lib.js
cli/startled/src/types.rs
cli/startled/testbed/Makefile
cli/startled/testbed/testbed.md

This pull request introduces version `0.2.0` of the `startled` CLI, bringing significant enhancements to metrics collection, reporting, and usability. The changes include the addition of new platform metrics, improved statistical reporting, and a redesigned HTML report layout. A new publishing guide has also been added to streamline the release process.
* **New Metrics**: Added platform metrics like `Response Latency`, `Response Duration`, `Runtime Overhead`, `Produced Bytes`, and `Runtime Done Duration` to JSON and HTML reports. [[1]](diffhunk://#diff-bd0cb949bb67fcfa38060059b5016cdb217ed459714094210b87496f0714b453R8-R26) [[2]](diffhunk://#diff-aff33bf4e337463eb1a6180a9b58b944752069b10f5ca6a932555ac84afe0573R16) [[3]](diffhunk://#diff-aff33bf4e337463eb1a6180a9b58b944752069b10f5ca6a932555a …

release: cli/startled v0.2.0

---

cli/startled/CHANGELOG.md
cli/startled/Cargo.toml
cli/startled/README.md
cli/startled/RELEASE_NOTES.md
cli/startled/src/main.rs
cli/startled/src/report.rs
cli/startled/src/screenshot.rs
cli/startled/src/templates/_sidebar.html
cli/startled/src/templates/chart.html
cli/startled/src/templates/css/style.css
cli/startled/src/templates/index.html
cli/startled/src/templates/js/lib.js
cli/startled/testbed/Makefile
cli/startled/testbed/testbed.md

This pull request introduces several updates to the `startled` CLI tool, focusing on enhancing HTML report visualization, improving user experience, and adding new features like combined chart views and local browsing support. Additionally, it includes code refactoring for maintainability and updates to documentation and release notes.
* Added a `--local-browsing` option to append 'index.html' to internal links for easier navigation when opening reports directly from the file system. This affects both the CLI (`main.rs`) and HTML generation logic (`report.rs`). [[1]](diffhunk://#diff-5fb52f72c3daaba5adfbdfaddaf0e2bc6b28ebbb5e4d9e8a4082eaf66b5d8886R166-R169) [[2]](diffhunk://#diff-5fb52f72c3daaba5adfbdfaddaf0e2bc6b28ebbb5e4d9e8a4082eaf66b5d8886R324) …

release: cli/startled v0.3.1

---

cli/startled/CHANGELOG.md
cli/startled/Cargo.toml
cli/startled/README.md
cli/startled/RELEASE_NOTES.md
cli/startled/testbed/functions/rust/collector/Cargo.toml
cli/startled/testbed/functions/rust/collector/src/main.rs

This pull request introduces several updates to the `startled` CLI project, including dependency updates, code formatting improvements, and documentation enhancements. The key changes are grouped into dependency management, codebase improvements, and documentation updates.
* Updated the version of the `startled` package in `cli/startled/Cargo.toml` from `0.3.2` to `0.3.3`.
* Removed the `serde_yaml` dependency and transitioned `tempfile` to use the workspace configuration in `cli/startled/Cargo.toml`. [[1]](diffhunk://#diff-112c3857fa8d5706869ef8ba5fdaee05097cf93d95f849ab39a4c1457fafa30bL26) [[2]](diffhunk://#diff-112c3857fa8d5706869ef8ba5fdaee05097cf93d95f849ab39a4c1457fafa30bL57-R56)
* Removed the `reqwest` dependency from the `collector` function in …

release cli/startled v0.3.3

---

Cargo.lock
cli/startled/CHANGELOG.md
cli/startled/Cargo.toml
cli/startled/PUBLISHING.md
cli/startled/README.md
cli/startled/RELEASE_NOTES.md
cli/startled/src/report.rs
cli/startled/src/templates/chart.html
cli/startled/src/templates/css/style.css
cli/startled/src/templates/index.html

This pull request introduces version `0.5.0` of the `startled` CLI tool, focusing on enhancing the educational value of its benchmarking reports by integrating AWS Lambda documentation-based metric descriptions. It also includes visual improvements, structural updates, and comprehensive testing for the new features.
* **AWS-Documentation-Based Metric Descriptions**: Added detailed descriptions to explain each metric's significance, AWS CloudWatch equivalents, and performance implications for cold starts, warm starts, and resource metrics. These descriptions are integrated into the `BarChartRenderData` and `LineChartRenderData` structs, and displayed in the HTML reports. [[1]](diffhunk://#diff-cf5a77c542971afe74e9afa350d67cb8676c3402f54374bad52106535c17f550R51) …

release: cli/startled v0.5.0

---

Cargo.lock
cli/startled/CHANGELOG.md
cli/startled/Cargo.toml
cli/startled/RELEASE_NOTES.md
cli/startled/src/report.rs
cli/startled/src/templates/chart.html
cli/startled/src/templates/css/style.css

This pull request introduces significant updates to the `startled` CLI tool, focusing on enhancing metric capabilities, improving naming consistency, and reorganizing navigation for better usability. The changes include the addition of new metrics, renaming existing metrics for consistency, and updating descriptions and tests to reflect these improvements.
* **Cold Start Resource Metrics**: Added charts for cold start memory usage and produced bytes, providing insights into resource consumption during Lambda initialization. (`cli/startled/src/report.rs`, [[1]](diffhunk://#diff-cf5a77c542971afe74e9afa350d67cb8676c3402f54374bad52106535c17f550R1071-R1176) [[2]](diffhunk://#diff-cf5a77c542971afe74e9afa350d67cb8676c3402f54374bad52106535c17f550L1610-R1714)
* **Complete Set of Warm Start …

release: cli/startled v0.6.0

---

cli/startled/CHANGELOG.md
cli/startled/Cargo.toml
cli/startled/README.md
cli/startled/src/report.rs
cli/startled/src/templates/_sidebar.html
cli/startled/src/templates/css/style.css
cli/startled/src/templates/js/lib.js

This pull request introduces version `0.7.0` of the `startled` CLI tool, focusing on enhancing report generation and navigation, improving code quality, and adding new features like summary pages and response latency metrics. The most significant changes include the implementation of summary pages, navigation enhancements, and the addition of new metrics.
* **Summary Pages**: Implemented comprehensive summary pages accessible via memory size links in navigation, displaying key metrics for comparative analysis across all functions. [[1]](diffhunk://#diff-bd0cb949bb67fcfa38060059b5016cdb217ed459714094210b87496f0714b453L1-R27) [[2]](diffhunk://#diff-aff33bf4e337463eb1a6180a9b58b944752069b10f5ca6a932555ac84afe0573R351-R356) [[3]](diffhunk://#diff-cf5a77c542971afe74e9afa350d67cb8676c3402f54374b …

Release startled v0.7.0

---

packages/rust/lambda-otel-lite/CHANGELOG.md
packages/rust/lambda-otel-lite/Cargo.toml
packages/rust/lambda-otel-lite/README.md
packages/rust/lambda-otel-lite/examples/handler/main.rs
packages/rust/lambda-otel-lite/examples/tower/main.rs
packages/rust/lambda-otel-lite/src/constants.rs
packages/rust/lambda-otel-lite/src/events.rs
packages/rust/lambda-otel-lite/src/extension.rs
packages/rust/lambda-otel-lite/src/extractors.rs
packages/rust/lambda-otel-lite/src/lib.rs
packages/rust/lambda-otel-lite/src/mode.rs
packages/rust/lambda-otel-lite/src/processor.rs
packages/rust/lambda-otel-lite/src/propagation.rs
packages/rust/lambda-otel-lite/src/telemetry.rs

This pull request introduces a significant update to the `lambda-otel-lite` crate, version 0.16.0, with a focus on enhancing OpenTelemetry support, adding a structured event logging system, and improving code clarity and maintainability. The most notable changes include the addition of the `events` module, breaking upgrades to OpenTelemetry dependencies, and various documentation enhancements.
* **New `events` module**:
- Provides structured event recording for OpenTelemetry spans.
- Includes dual APIs: function-based (`record_event`) and builder-based (`event()`).
- Supports level-based filtering, individual and batch attributes, and automatic span integration. [[1]](diffhunk://#diff-186498266ac8e953c6310f423de26221c85a117655d116518dd6abf581d93900R10-R41) …

release: rust/lambda-otel-lite v0.16.0
