packages/python/adapter/CHANGELOG.md, packages/python/adapter/pyproject.toml
- Bump version from 0.1.0 to 0.1.1
- Update dependency specifications in `pyproject.toml` to support newer OpenTelemetry releases
- Update CHANGELOG.md to document changes
The package had outdated dependency constraints that made it incompatible with newer releases of OpenTelemetry.
Updated version constraints to support newer OpenTelemetry releases while maintaining compatibility.
=> chore(adapter): bump version to 0.1.1 and fix dependency specs

packages/node/exporter/README.md
The `context` parameter in the handler hides the `context` from `@opentelemetry/api`
=> Fixing name clash in example

packages/rust/otlp-stdout-span-exporter/CHANGELOG.md
This pull request updates the changelog for the `otlp-stdout-span-exporter` package. The most important change is the version bump to align with other related packages.
Changes to the changelog:
* [`packages/rust/otlp-stdout-span-exporter/CHANGELOG.md`](diffhunk://#diff-51c986c5bb8e2e0e9f9c5ecc6f5ac74d2f94a63485f77b241081dc12820081ffL8-R23): Updated the version to 0.6.0 and added a note about the version bump to align with `lambda-otel-utils` and other packages.
=> chore(otlp-stdout-span-exporter): bump version to 0.6.0

experimental/otlp-stdout-kinesis-processor/extension/layer/Cargo.toml, experimental/otlp-stdout-kinesis-processor/extension/layer/Makefile, experimental/otlp-stdout-kinesis-processor/extension/samconfig.toml, experimental/otlp-stdout-kinesis-processor/extension/template.yaml
This pull request includes several updates to the `otlp-stdout-kinesis-processor` extension to improve its configuration and build process. The most important changes include renaming the package, updating dependencies to use workspace settings, modifying the Makefile for better build output management, and adding build parameters to the SAM configuration.
Configuration and dependencies updates:
* [`experimental/otlp-stdout-kinesis-processor/extension/layer/Cargo.toml`](diffhunk://#diff-d86c962401bcfc47aa9f6750bf91d6c99221c0d19b74fa01c43201901eec75f4L2-L17): Renamed the package to `otlp-stdout-kinesis-extension-layer`, updated dependencies to use workspace settings for `authors`, `license`, `tokio`, `tracing`, and `aws-config`.
Build process improvements:
* …
=> feat: update OTLP stdout Kinesis processor configuration and dependencies

.github/workflows/publish-python-lambda-otel-lite.yml
This pull request includes a small but important change to the `.github/workflows/publish-python-lambda-otel-lite.yml` file. The change adds necessary permissions for the workflow to function correctly.
Permissions added:
* `contents: write` - Needed for pushing tags
* `id-token: write` - Needed for publishing to PyPI
=> ci: add required permissions for GitHub Actions workflow

packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/__tests__/handler.test.ts, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/internal/telemetry/extractors.ts
This pull request includes updates to the `lambda-otel-lite` package to improve attribute extraction consistency and fix issues with API Gateway v2 event handling. The changes include updates to the `CHANGELOG.md`, `package.json`, and several extractor functions.
* [`packages/node/lambda-otel-lite/CHANGELOG.md`](diffhunk://#diff-639c39db47031fa119e62d0d1eb34488b39daf098c3a267200c598fd8989384dR8-R13): Documented the changes for version 0.8.1, including the fix for API Gateway v2 event extraction and alignment of attribute extraction behavior between Python and Node.js implementations.
* [`packages/node/lambda-otel-lite/package.json`](diffhunk://#diff-5816b4f7130d9fd72e716b0a8a8b5f10ae23ac4add56516d6afb81d7fe31e2d0L3-R3): Updated the version from 0.8.0 to 0.8.1.
* …
=> Release/node lambda otel lite 0.8.1

.github/workflows/publish-node-lambda-otel-lite.yml, packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/PUBLISHING.md, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/version.ts
This pull request includes several changes aimed at ensuring version consistency between `package.json` and `src/version.ts`, as well as updating documentation and workflows accordingly.
* [`.github/workflows/publish-node-lambda-otel-lite.yml`](diffhunk://#diff-263fbeb601c9a1874edd8f0a3922d4787f18d9e2396959c5ba53dd6cdc27894cR89-R95): Added a step to verify that the version in `package.json` matches the version in `src/version.ts` before publishing.
* [`packages/node/lambda-otel-lite/package.json`](diffhunk://#diff-5816b4f7130d9fd72e716b0a8a8b5f10ae23ac4add56516d6afb81d7fe31e2d0L3-R3): Updated the version to `0.9.1`.
* [`packages/node/lambda-otel-lite/src/version.ts`](diffhunk://#diff-691bd3ab607ea739e3de7cfce9f353f83de4000e15510ed62c81680d3cb365b8L9-R9): Updated the version to `0.9.1` to …
=> Release/node lambda otel lite 0.9.1

packages/python/lambda_otel_lite/CHANGELOG.md, packages/python/lambda_otel_lite/README.md, packages/python/lambda_otel_lite/examples/handler/app.py, packages/python/lambda_otel_lite/pyproject.toml, packages/python/lambda_otel_lite/src/lambda_otel_lite/__init__.py, packages/python/lambda_otel_lite/src/lambda_otel_lite/telemetry.py
This pull request includes multiple changes to the `lambda_otel_lite` package, focusing on version updates, code refactoring, and documentation updates. The most important changes include version bumping, refactoring the `get_lambda_resource` function, and removing the release instructions from the `README.md`.
Version updates:
* [`packages/python/lambda_otel_lite/pyproject.toml`](diffhunk://#diff-1860126e0eaa261a6df72839e6a152cdc01af3d073bd1bfc763d2ad7fb333a4eL7-R7): Updated the version from `0.8.2` to `0.9.0`.
* [`packages/python/lambda_otel_lite/src/lambda_otel_lite/__init__.py`](diffhunk://#diff-846f926ecbfefc0ef2a514893a354260895ec60ec74e698b970fc5180e7b8830L12-R12): Updated the `__version__` from `0.8.2` to `0.9.0`.
* [`packages/python/lambda_otel_lite/CHANGELOG.md`](diffhunk://#diff …
=> Release/python lambda otel lite 0.9.0

.github/workflows/publish-rust-otlp-stdout-span-exporter.yml, Cargo.lock, Cargo.toml, packages/rust/otlp-stdout-span-exporter/CHANGELOG.md, packages/rust/otlp-stdout-span-exporter/Cargo.toml, packages/rust/otlp-stdout-span-exporter/PUBLISHING.md, packages/rust/otlp-stdout-span-exporter/README.md, packages/rust/otlp-stdout-span-exporter/examples/hello.rs, packages/rust/otlp-stdout-span-exporter/src/lib.rs
This pull request introduces several changes to the Rust OTLP Stdout Span Exporter package, including the addition of a GitHub Actions workflow for publishing, version updates, and enhancements to the exporter functionality and documentation.
* Added a new GitHub Actions workflow to automate testing and publishing of the Rust OTLP Stdout Span Exporter package. The workflow triggers on pull requests and pushes to the main branch, running tests on both x64 and arm64 architectures, and publishing to crates.io if tests pass. (`.github/workflows/publish-rust-otlp-stdout-span-exporter.yml`)
* Updated the package version to `0.9.0` and upgraded OpenTelemetry dependencies to version `0.28.0`. (`Cargo.toml`) [[1]](diffhunk://#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542L17- …
=> Release otlp-stdout-span-exporter v0.9.0

.github/workflows/publish-rust-lambda-otel-lite.yml, packages/rust/lambda-otel-lite/CHANGELOG.md, packages/rust/lambda-otel-lite/Cargo.toml, packages/rust/lambda-otel-lite/PUBLISHING.md, packages/rust/lambda-otel-lite/README.md, packages/rust/lambda-otel-lite/examples/Cargo.toml, packages/rust/lambda-otel-lite/examples/handler/main.rs, packages/rust/lambda-otel-lite/examples/template.yaml, packages/rust/lambda-otel-lite/examples/tower/main.rs, packages/rust/lambda-otel-lite/src/extension.rs, packages/rust/lambda-otel-lite/src/handler.rs, packages/rust/lambda-otel-lite/src/layer.rs, packages/rust/lambda-otel-lite/src/lib.rs, packages/rust/lambda-otel-lite/src/logger.rs, packages/rust/lambda-otel-lite/src/mode.rs, packages/rust/lambda-otel-lite/src/processor.rs, packages/rust/lambda-otel-lite/src/resource.rs, packages/rust/lambda-otel-lite/src/telemetry.rs, packages/rust/lambda-otel-utils/Cargo.toml, packages/rust/lambda-otel-utils/examples/tracing_example.rs, packages/rust/lambda-otel-utils/src/http_meter_provider.rs, packages/rust/lambda-otel-utils/src/http_tracer_provider.rs, packages/rust/lambda-otel-utils/src/resource.rs, packages/rust/lambda-otel-utils/src/subscriber.rs
This pull request includes several significant updates to the Rust Lambda OTel Lite package, focusing on workflow automation, version updates, and documentation improvements. The most important changes include the addition of a GitHub Actions workflow for automated publishing, updates to the `Cargo.toml` dependencies, and extensive updates to the `CHANGELOG.md` and `README.md` files to reflect new features and breaking changes.
* [`.github/workflows/publish-rust-lambda-otel-lite.yml`](diffhunk://#diff-7c7f2e57b880ccb60948479759186fbd39aa3c96ff73a0a9e5764034ac976f03R1-R104): Added a GitHub Actions workflow to automate testing and publishing of the Rust Lambda OTel Lite package on merges to the main branch. This workflow includes steps for setting up the Rust toolchain, caching …
=> Release/rust lambda otel lite 0.9.0

.github/workflows/publish-rust-otlp-sigv4-client.yml, .github/workflows/publish-rust-otlp-stdout-client.yml
This pull request includes several updates to GitHub Actions workflows for Rust packages. The changes focus on improving the versioning and tagging process, as well as adding a new workflow for the `otlp-sigv4-client` package.
Improvements to existing workflows:
* [`.github/workflows/publish-rust-lambda-otel-lite.yml`](diffhunk://#diff-7c7f2e57b880ccb60948479759186fbd39aa3c96ff73a0a9e5764034ac976f03R38): Added a condition to run the job only on specific events and updated the version verification and tagging logic to include the full package path in the tag name. [[1]](diffhunk://#diff-7c7f2e57b880ccb60948479759186fbd39aa3c96ff73a0a9e5764034ac976f03R38) [[2]](diffhunk://#diff-7c7f2e57b880ccb60948479759186fbd39aa3c96ff73a0a9e5764034ac976f03R88-R98) …
=> Standardize Rust package workflow files

.github/workflows/publish-rust-lambda-otel-lite.yml, packages/rust/lambda-otel-lite/CHANGELOG.md, packages/rust/lambda-otel-lite/Cargo.toml
This pull request includes updates to the `lambda-otel-lite` package, primarily focusing on version updates for dependencies and the package itself. The most important changes include updating the `otlp-stdout-span-exporter` dependency and the package version.
Dependency updates:
* [`packages/rust/lambda-otel-lite/Cargo.toml`](diffhunk://#diff-26cd2b53f6926e62cfe6fcd00f3950088acef5a9ca350092c42550bd5b1ad5c8L22-R22): Updated `otlp-stdout-span-exporter` dependency to version 0.10.0.
Version updates:
* [`packages/rust/lambda-otel-lite/Cargo.toml`](diffhunk://#diff-26cd2b53f6926e62cfe6fcd00f3950088acef5a9ca350092c42550bd5b1ad5c8L3-R3): Updated the package version to 0.10.0.
* [`packages/rust/lambda-otel-lite/CHANGELOG.md`](diffhunk://#diff-186498266ac8e953c6310f423de26221c85a117655d116518dd6ab …
=> Release packages/rust/lambda-otel-lite 0.10.0

packages/node/otlp-stdout-span-exporter/.gitignore, packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/PUBLISHING.md, packages/node/otlp-stdout-span-exporter/examples/simple-stdout-hello.ts, packages/node/otlp-stdout-span-exporter/package-lock.json, packages/node/otlp-stdout-span-exporter/package.json, packages/node/otlp-stdout-span-exporter/src/version.ts
This pull request includes multiple changes to the `packages/node/otlp-stdout-span-exporter` package, focusing on version updates, documentation improvements, and example additions. The most important changes include updating the package version and dependencies, adding a publishing checklist, and providing a simple usage example.
* [`packages/node/otlp-stdout-span-exporter/package.json`](diffhunk://#diff-de9bcc5499221be2efd6fb53ecc3d3967208154d47830f6f69e94693d1ffafbeL3-R3): Updated the package version from `0.1.0` to `0.10.0` and upgraded several dependencies, including `@opentelemetry/core`, `@opentelemetry/sdk-trace-base`, and `@opentelemetry/api`. [[1]](diffhunk://#diff-de9bcc5499221be2efd6fb53ecc3d3967208154d47830f6f69e94693d1ffafbeL3-R3) …
=> Release node otlp stdout span exporter v0.10.0 

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/README.md, packages/node/otlp-stdout-span-exporter/package.json, packages/node/otlp-stdout-span-exporter/src/__tests__/otlp_stdout_span_exporter.test.ts, packages/node/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter.ts
This pull request introduces several enhancements and updates to the `otlp-stdout-span-exporter` package. The most significant changes include the addition of support for configuring the GZIP compression level via an environment variable, improvements to documentation, and updates to unit tests to cover the new functionality.
* Added support for the `OTLP_STDOUT_SPAN_EXPORTER_COMPRESSION_LEVEL` environment variable to configure the GZIP compression level. [[1]](diffhunk://#diff-98d7656b1775668a361eb259643823fb60356e4f05cc19ce00f0d804403e6012R8-R15) [[2]](diffhunk://#diff-d6a5b3bd2fc0e553dfdf7d0767e4f582b05299acec680509bf03f06c6a7eb821R9-R19)
* Improved documentation to align with the Python and Rust implementations and updated the code example to use current OpenTelemetry API patterns. …
=> Release node otlp-stdout-span-exporter v0.10.1

forwarders/experimental/aws-span-processor/processor/Cargo.toml, forwarders/experimental/aws-span-processor/template.yaml, forwarders/experimental/otlp-stdout-kinesis-processor/processor/Cargo.toml, forwarders/otlp-stdout-logs-processor/template.yaml
This pull request includes several changes to the `forwarders/experimental/aws-span-processor` and `forwarders/experimental/otlp-stdout-logs-processor` components, focusing on renaming resources and updating dependencies. The most important changes are listed below:
* Renamed `SpanProcessorFunction` to `SpansProcessorFunction` in `template.yaml` for AWS Span Processor. This change affects multiple references within the file. [[1]](diffhunk://#diff-a9df9e326d219b9a05189a86e4b7be28121f66e4162dd1ff9d342d37e6a9008bL32-R32) [[2]](diffhunk://#diff-a9df9e326d219b9a05189a86e4b7be28121f66e4162dd1ff9d342d37e6a9008bL90-R107)
* Renamed `OtlpStdoutProcessor` to `LogsProcessorFunction` in `template.yaml` for OTLP Stdout Logs Processor. This change affects multiple references within the file. …
=> refactor: Rename Lambda function and resource names for clarity

.github/workflows/publish-node-lambda-otel-lite.yml, packages/node/lambda-otel-lite/.gitignore, packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/PUBLISHING.md, packages/node/lambda-otel-lite/__tests__/telemetry/completion.test.ts, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/internal/telemetry/completion.ts, packages/node/lambda-otel-lite/src/version.ts
This pull request includes several changes to improve version management and streamline the publishing process for the `@dev7a/lambda-otel-lite` package. The most important changes include updating the versioning approach, modifying the CI/CD pipeline, and updating documentation and tests accordingly.
Version management improvements:
* [`packages/node/lambda-otel-lite/package.json`](diffhunk://#diff-5816b4f7130d9fd72e716b0a8a8b5f10ae23ac4add56516d6afb81d7fe31e2d0L3-R3): Updated the version to `0.10.0` and added a script to auto-generate the `version.ts` file during the build process. [[1]](diffhunk://#diff-5816b4f7130d9fd72e716b0a8a8b5f10ae23ac4add56516d6afb81d7fe31e2d0L3-R3) [[2]](diffhunk://#diff-5816b4f7130d9fd72e716b0a8a8b5f10ae23ac4add56516d6afb81d7fe31e2d0L49-R53)
* …
=> Release node lambda-otel-lite v0.10.0

packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/README.md, packages/node/lambda-otel-lite/__tests__/telemetry/init.test.ts, packages/node/lambda-otel-lite/package-lock.json, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/internal/telemetry/init.ts, packages/node/lambda-otel-lite/src/version.ts
This pull request includes several updates to the `lambda-otel-lite` package, focusing on adding support for custom context propagators, updating dependencies, and enhancing tests. Below is a summary of the most important changes:
* Added support for custom context propagators via the `propagators` option in `initTelemetry` and included documentation and examples for using custom propagators. [[1]](diffhunk://#diff-639c39db47031fa119e62d0d1eb34488b39daf098c3a267200c598fd8989384dR8-R19) [[2]](diffhunk://#diff-76a27bbd9a88291b658226c6a2f1ba27ebe4acd0bf04682df64de7b0ce9918baR146-R148) [[3]](diffhunk://#diff-76a27bbd9a88291b658226c6a2f1ba27ebe4acd0bf04682df64de7b0ce9918baL171-R185) [[4]](diffhunk://#diff-76a27bbd9a88291b658226c6a2f1ba27ebe4acd0bf04682df64de7b0ce9918baR206-R220)
* Updated …
=> Release node lambda-otel-lite 0.10.1

packages/python/lambda-otel-lite/CHANGELOG.md, packages/python/lambda-otel-lite/README.md, packages/python/lambda-otel-lite/examples/README.md, packages/python/lambda-otel-lite/pyproject.toml, packages/python/lambda-otel-lite/src/lambda_otel_lite/telemetry.py, packages/python/lambda-otel-lite/tests/test_telemetry.py
This pull request includes several changes to the `lambda-otel-lite` project, focusing on adding support for custom context propagators, updating dependencies, and including new examples for usage. Below are the most important changes:
* Added support for custom context propagators via the `propagators` parameter in the `init_telemetry` function. [[1]](diffhunk://#diff-c1cdecd0d4dbd084a18cefc24333eb43808caa045a2f359596ad7c9143f4f647R205) [[2]](diffhunk://#diff-c1cdecd0d4dbd084a18cefc24333eb43808caa045a2f359596ad7c9143f4f647R218-R221) [[3]](diffhunk://#diff-c1cdecd0d4dbd084a18cefc24333eb43808caa045a2f359596ad7c9143f4f647R231-R239)
* Included tests for the custom propagator functionality to ensure proper integration.
* Added a new section in `examples/README.md` to demonstrate how to use …
=> Release python lambda-otel-lite 0.10.1

packages/rust/lambda-otel-lite/CHANGELOG.md, packages/rust/lambda-otel-lite/Cargo.toml, packages/rust/lambda-otel-lite/examples/README.md, packages/rust/lambda-otel-lite/examples/template.yaml, packages/rust/lambda-otel-lite/src/telemetry.rs
This pull request includes several important updates and improvements to the `lambda-otel-lite` package. The changes mainly focus on adding new features, updating configurations, enhancing documentation, and improving example templates.
- Added support for controlling the `fmt` layer through the `LAMBDA_TRACING_ENABLE_FMT_LAYER` environment variable.
- Introduced tests to verify the handling of the `fmt` layer configuration via environment variables.
- Updated the `TelemetryConfig::default()` implementation to read from environment variables, enabling the `fmt` layer based on the `LAMBDA_TRACING_ENABLE_FMT_LAYER` variable.
- Changed the `ApplicationLogLevel` from DEBUG to INFO in the `template.yaml` file and example templates. [[1]](diffhunk://#diff-b760c127f868a8fd9ee7f973e59c411b481942f9 …
=> Release rust lambda-otel-lite v0.10.2

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/PUBLISHING.md, packages/node/otlp-stdout-span-exporter/README.md, packages/node/otlp-stdout-span-exporter/package.json, packages/node/otlp-stdout-span-exporter/src/__tests__/otlp_stdout_span_exporter.test.ts, packages/node/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter.ts
This pull request includes several changes to the `@dev7a/otlp-stdout-span-exporter` package, focusing on improving configuration precedence, updating documentation, and refining error handling. The most important changes are summarized below:
* Modified the configuration value precedence to ensure environment variables always take precedence over constructor parameters. Enhanced error handling for invalid environment variable values. [[1]](diffhunk://#diff-98d7656b1775668a361eb259643823fb60356e4f05cc19ce00f0d804403e6012R8-R14) [[2]](diffhunk://#diff-0b74609b17a83ab78303de879512381862895897acb22edf246633a8c5c497d0L108-R116) [[3]](diffhunk://#diff-d6a5b3bd2fc0e553dfdf7d0767e4f582b05299acec680509bf03f06c6a7eb821L82-L108)
* Updated the `README.md` to clearly explain the configuration …
=> release node otlp-stdout-span-exporter v0.11.0

packages/python/otlp-stdout-span-exporter/CHANGELOG.md, packages/python/otlp-stdout-span-exporter/PUBLISHING.md, packages/python/otlp-stdout-span-exporter/README.md, packages/python/otlp-stdout-span-exporter/pyproject.toml, packages/python/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter/__init__.py, packages/python/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter/constants.py, packages/python/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter/exporter.py, packages/python/otlp-stdout-span-exporter/tests/test_otlp_stdout_span_exporter.py
This pull request includes several significant changes to the `otlp-stdout-span-exporter` package, focusing on adding a new constants module, improving configuration handling, and enhancing documentation. Below is a summary of the most important changes:
* Added a new constants module that exports `EnvVars`, `Defaults`, and `ResourceAttributes` classes. [[1]](diffhunk://#diff-e14c6c1119e1a8b095bac5f2c1015beafb1c1926f41803f3c8e3691eb11bbf72R5-R17) [[2]](diffhunk://#diff-ac25b49e75a4d28aa37ad68e4360f00a6c43d015ab2e244d37ee2e966d0039e4R1-R34)
* Improved documentation for configuration precedence rules and updated the README to reflect these changes. [[1]](diffhunk://#diff-e14c6c1119e1a8b095bac5f2c1015beafb1c1926f41803f3c8e3691eb11bbf72R5-R17) …
=> release python otlp-stdout-span-exporter v0.11.0

forwarders/experimental/aws-span-processor/processor/src/main.rs, forwarders/experimental/aws-span-processor/processor/src/otlp.rs, forwarders/experimental/aws-span-processor/samconfig.toml
This pull request includes several changes to the `forwarders/experimental/aws-span-processor/processor/src/otlp.rs` file, focusing on enhancing the span conversion functionality and adding comprehensive test cases. Additionally, there are modifications to the `samconfig.toml` file and test data in `main.rs`.
Enhancements to span conversion and decoding:
* Added a `decode_hex` function to convert hex strings to bytes, handling various formats and filtering out non-hex characters. (`forwarders/experimental/aws-span-processor/processor/src/otlp.rs`)
* Updated `convert_span_to_otlp_protobuf` to use `decode_hex` for `traceId`, `spanId`, and `parentSpanId`, and to convert events from the span record. (`forwarders/experimental/aws-span-processor/processor/src/otlp.rs`) …
=> feat: improved AWS span processor

benchmark/functions/rust/grpc/Cargo.toml, benchmark/functions/rust/grpc/src/main.rs, benchmark/functions/rust/http/Cargo.toml, benchmark/functions/rust/http/src/main.rs, benchmark/functions/rust/stdout/Cargo.toml, benchmark/functions/rust/stdout/src/main.rs, benchmark/proxy/src/main.rs, benchmark/template.yaml
This pull request includes significant updates to the Rust-based benchmark functions, adding support for OpenTelemetry tracing and enhancing the AWS Lambda functions. The changes include new dependencies, handlers, and configurations for various Rust functions, as well as updates to the benchmark template to include these new functions.
* [`benchmark/functions/rust/grpc/Cargo.toml`](diffhunk://#diff-e3653b1708d8235337bc2584716b21deb465601a97052a1306e05f6961e008b4R1-R29): Added a new `benchmark-functions-rust-grpc` package with dependencies and configuration for OpenTelemetry.
* [`benchmark/functions/rust/grpc/src/main.rs`](diffhunk://#diff-e9977d8801f646f899fb83b34f98b23afbe643725cb84959a028b0c5c6be2ac5R1-R178): Implemented a Lambda handler that creates a tree of spans to measure …
=> feat: add Rust Lambda functions for OpenTelemetry benchmarks

packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/README.md, packages/node/lambda-otel-lite/__tests__/test_exports.ts, packages/node/lambda-otel-lite/__tests__/test_resource.ts, packages/node/lambda-otel-lite/examples/handler/app.js, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/extractors/index.ts, packages/node/lambda-otel-lite/src/index.ts, packages/node/lambda-otel-lite/src/internal/telemetry/processor.ts
This pull request includes several changes to the `lambda-otel-lite` package, focusing on adding a new subpath for extractors, updating documentation, and enhancing test coverage. The most important changes include the addition of a dedicated extractors subpath, updates to the documentation to reflect the new import patterns, and new tests to ensure proper package exports.
* Added a missing `./extractors` subpath to package exports in `package.json` to fix import errors and created a dedicated extractors directory for cleaner imports. [[1]](diffhunk://#diff-5816b4f7130d9fd72e716b0a8a8b5f10ae23ac4add56516d6afb81d7fe31e2d0R38-R41) [[2]](diffhunk://#diff-639c39db47031fa119e62d0d1eb34488b39daf098c3a267200c598fd8989384dR10-R16)
* Re-exported all extractors from the internal module in …
=> release node lambda-otel-lite v0.11.1

packages/rust/lambda-otel-lite/CHANGELOG.md, packages/rust/lambda-otel-lite/Cargo.toml, packages/rust/lambda-otel-lite/src/resource.rs
This pull request includes several changes to the `lambda-otel-lite` package. The most important changes are the addition of fallback logic for setting the service name, updating the package version, and importing a new module for default constants.
* **Service Name Fallback Logic**:
- Updated `get_lambda_resource` function to include fallback logic for setting the service name. It now checks for `OTEL_SERVICE_NAME`, falls back to `AWS_LAMBDA_FUNCTION_NAME`, and defaults to "unknown_service" if neither is available (`packages/rust/lambda-otel-lite/src/resource.rs`).
* **Version Update**:
- Updated the package version from `0.11.0` to `0.11.1` in the `Cargo.toml` file (`packages/rust/lambda-otel-lite/Cargo.toml`).
* **Changelog Update**:
- Added a new entry for version `0.11.1` in the …
=> release rust lambda-otel-lite v0.11.1

forwarders/experimental/aws-span-processor/processor/src/main.rs, forwarders/experimental/aws-span-processor/processor/src/otlp.rs, forwarders/experimental/otlp-stdout-kinesis-processor/processor/src/main.rs
This pull request includes several changes to improve code formatting and organization in the AWS span processor and OTLP stdout Kinesis processor. The most important changes include reordering imports, adding context to error handling, and improving code readability in various functions and tests.
Code formatting and organization:
* [`forwarders/experimental/aws-span-processor/processor/src/main.rs`](diffhunk://#diff-493c80d2cb992c9473291c405f1d15148f59245a83eec18a54e7ac02536bf444L18-R29): Reordered imports for better readability and consistency.
* [`forwarders/experimental/otlp-stdout-kinesis-processor/processor/src/main.rs`](diffhunk://#diff-d30b18f90993c20bb490bacd86509cb7a97e47d7acd4cb775787bea6b6a3a049L18-R31): Reordered imports and improved code formatting in various functions. …
=> refactor: improve code formatting in forwarders processors

packages/rust/lambda-otel-lite/CHANGELOG.md, packages/rust/lambda-otel-lite/Cargo.toml, packages/rust/lambda-otel-lite/src/constants.rs, packages/rust/lambda-otel-lite/src/telemetry.rs
This pull request includes several changes to the `lambda-otel-lite` package to enhance logging configuration and update the version. The most important changes include adding support for controlling console logging output via an environment variable, updating the version, and modifying the telemetry configuration.
Enhancements to logging configuration:
* [`packages/rust/lambda-otel-lite/src/constants.rs`](diffhunk://#diff-12ef7660237b8592ada3c92cfb4992335f23fb3492c8681cd775630d1835dbfdR32-R35): Added a new environment variable `LAMBDA_TRACING_ENABLE_FMT_LAYER` to control console logging output without code changes. [[1]](diffhunk://#diff-12ef7660237b8592ada3c92cfb4992335f23fb3492c8681cd775630d1835dbfdR32-R35) [[2]](diffhunk://#diff-12ef7660237b8592ada3c92cfb4992335f23fb3492c8681cd775630d1 …
=> release rust lambda-otel-lite v0.11.2

packages/python/lambda-otel-lite/CHANGELOG.md, packages/python/lambda-otel-lite/README.md, packages/python/lambda-otel-lite/pyproject.toml, packages/python/lambda-otel-lite/src/lambda_otel_lite/telemetry.py, packages/python/lambda-otel-lite/tests/test_telemetry.py
This pull request introduces support for custom ID generators in the `lambda-otel-lite` package, along with associated documentation and version updates. The most important changes include adding the `id_generator` parameter to the `init_telemetry` function, updating the documentation, and adding tests for the new functionality.
Support for custom ID generators:
* [`packages/python/lambda-otel-lite/src/lambda_otel_lite/telemetry.py`](diffhunk://#diff-c1cdecd0d4dbd084a18cefc24333eb43808caa045a2f359596ad7c9143f4f647R123): Added the `id_generator` parameter to the `init_telemetry` function and updated the `TracerProvider` initialization to use the provided ID generator. [[1]](diffhunk://#diff-c1cdecd0d4dbd084a18cefc24333eb43808caa045a2f359596ad7c9143f4f647R123) …
=> release python lambda-otel-lite v0.12.0

packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/__tests__/test_init.ts, packages/node/lambda-otel-lite/examples/README.md, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/internal/telemetry/init.ts
This pull request includes several changes to add support for custom ID generators in the `lambda-otel-lite` package, along with updates to documentation and tests. The most important changes include adding the `idGenerator` option to `initTelemetry`, updating the test suite to cover this new functionality, and updating the documentation to reflect these changes.
* [`packages/node/lambda-otel-lite/src/internal/telemetry/init.ts`](diffhunk://#diff-76a27bbd9a88291b658226c6a2f1ba27ebe4acd0bf04682df64de7b0ce9918baR54-R56): Added the `idGenerator` option to the `initTelemetry` function to allow custom ID generators, such as AWS X-Ray compatible ID generators. [[1]](diffhunk://#diff-76a27bbd9a88291b658226c6a2f1ba27ebe4acd0bf04682df64de7b0ce9918baR54-R56) …
=> release node lambda-otel-lite v0.11.2

packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/README.md, packages/node/lambda-otel-lite/__tests__/test_exports.ts, packages/node/lambda-otel-lite/package.json
This pull request includes updates to the `lambda-otel-lite` package, with changes to the changelog, documentation, tests, and package version. The most important changes are summarized below:
* Added a new release entry for version 0.11.3, which includes a package release fix to ensure all required files are included in the release. There are no functional changes from version 0.11.2.
* Added a new section in the README for custom configuration with an ID generator, including an example of how to use the AWS X-Ray ID generator. [[1]](diffhunk://#diff-3f14b3187ed47a0cef26dfccfc088aa10aa5dae68add235626f5ee99ff8d94ddR25) [[2]](diffhunk://#diff-3f14b3187ed47a0cef26dfccfc088aa10aa5dae68add235626f5ee99ff8d94ddR300-R319)
* Reformatted the `test_exports.ts` file for better readability by …
=> release node lambda-otel-lite v0.11.3

packages/rust/otlp-stdout-span-exporter/CHANGELOG.md, packages/rust/otlp-stdout-span-exporter/Cargo.toml
This pull request includes updates to the `otlp-stdout-span-exporter` package to improve consistency and API access, as well as enhancements to the test implementation.
* [`packages/rust/otlp-stdout-span-exporter/CHANGELOG.md`](diffhunk://#diff-51c986c5bb8e2e0e9f9c5ecc6f5ac74d2f94a63485f77b241081dc12820081ffR10-R16): Updated dependencies to use workspace references for better consistency and made `ExporterOutput` struct and fields public for improved API access.
* [`packages/rust/otlp-stdout-span-exporter/CHANGELOG.md`](diffhunk://#diff-51c986c5bb8e2e0e9f9c5ecc6f5ac74d2f94a63485f77b241081dc12820081ffR10-R16): Improved test implementation using the builder pattern.
* [`packages/rust/otlp-stdout-span-exporter/Cargo.toml`](diffhunk://#diff-139d37c5c8f0270080968f69d2217b6dc710f974739d4ef4f2b74 …
=> release rust otlp-stdout-span-exporter v0.11.1

packages/rust/otlp-stdout-span-exporter/CHANGELOG.md, packages/rust/otlp-stdout-span-exporter/Cargo.toml, packages/rust/otlp-stdout-span-exporter/PUBLISHING.md, packages/rust/otlp-stdout-span-exporter/README.md, packages/rust/otlp-stdout-span-exporter/examples/simple-stdout-hello.rs, packages/rust/otlp-stdout-span-exporter/src/constants.rs, packages/rust/otlp-stdout-span-exporter/src/lib.rs
This pull request includes several significant updates to the `otlp-stdout-span-exporter` package, focusing on adding new features, updating documentation, and improving the version management process.
* Added an optional `level` field in the output to facilitate easier filtering in log aggregation systems. Introduced a `LogLevel` enum with `Debug`, `Info`, `Warn`, and `Error` variants, and an environment variable `OTLP_STDOUT_SPAN_EXPORTER_LOG_LEVEL` to set the log level.
* Added support for named pipe output as an alternative to stdout. Introduced the `OTLP_STDOUT_SPAN_EXPORTER_OUTPUT_TYPE` environment variable to control output type ("pipe" or "stdout") and a builder method `pipe(bool)` to configure named pipe output programmatically.
* Updated `CHANGELOG.md` to reflect the new version …
=> Release/rust/otlp stdout span exporter v0.13.0

packages/rust/lambda-otel-lite/CHANGELOG.md, packages/rust/lambda-otel-lite/Cargo.toml, packages/rust/lambda-otel-lite/PUBLISHING.md, packages/rust/lambda-otel-lite/README.md, packages/rust/lambda-otel-lite/examples/template.yaml, packages/rust/lambda-otel-lite/src/mode.rs, packages/rust/lambda-otel-lite/src/propagation.rs, packages/rust/lambda-otel-lite/src/telemetry.rs
This pull request to `packages/rust/lambda-otel-lite` includes several updates, primarily focusing on adding new features, improving configuration options, and enhancing logging. The most important changes include adding the ability to programmatically set the processor mode, updating the version and dependencies, and improving the documentation and publishing process.
* Added the ability to programmatically set the processor mode via `TelemetryConfig.processor_mode` and introduced the `ProcessorMode::resolve()` method to handle both environment variable and programmatic configuration (`CHANGELOG.md`, `README.md`, `mode.rs`, `telemetry.rs`). [[1]](diffhunk://#diff-186498266ac8e953c6310f423de26221c85a117655d116518dd6abf581d93900R10-R15) …
=> release: rust/lambda-otel-lite v0.13.0

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/PUBLISHING.md, packages/node/otlp-stdout-span-exporter/README.md, packages/node/otlp-stdout-span-exporter/examples/simple-stdout-hello.ts, packages/node/otlp-stdout-span-exporter/package-lock.json, packages/node/otlp-stdout-span-exporter/package.json, packages/node/otlp-stdout-span-exporter/src/__tests__/otlp_stdout_span_exporter.test.ts, packages/node/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter.ts
This pull request introduces several new features and improvements to the `@dev7a/otlp-stdout-span-exporter` package. The key changes include adding support for log levels and named pipe output, updating documentation, and modifying the publishing process.
* Added optional `level` field in the output for easier filtering in log aggregation systems.
* Introduced `LogLevel` enum with `Debug`, `Info`, `Warn`, and `Error` variants.
* Added `OTLP_STDOUT_SPAN_EXPORTER_LOG_LEVEL` environment variable to set the log level.
* Added support for named pipe output as an alternative to stdout.
* Added `OTLP_STDOUT_SPAN_EXPORTER_OUTPUT_TYPE` environment variable to control output type ("pipe" or "stdout").
* Updated `README.md` to include new configuration options for log level and output type. …
=> release: node/otlp-stdout-span-exporter v0.13.0

packages/python/otlp-stdout-span-exporter/CHANGELOG.md, packages/python/otlp-stdout-span-exporter/PUBLISHING.md, packages/python/otlp-stdout-span-exporter/README.md, packages/python/otlp-stdout-span-exporter/examples/simple_stdout_hello.py, packages/python/otlp-stdout-span-exporter/pyproject.toml, packages/python/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter/constants.py, packages/python/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter/exporter.py, packages/python/otlp-stdout-span-exporter/tests/test_otlp_stdout_span_exporter.py
This pull request introduces several new features and improvements to the `otlp-stdout-span-exporter` package. The changes include adding support for log levels, named pipe output, and enhancing error handling and documentation.
* Added `LogLevel` enum with `DEBUG`, `INFO`, `WARN`, and `ERROR` variants.
* Introduced `OutputType` enum with `STDOUT` and `PIPE` variants and the `Output` abstract class with implementations for stdout and named pipe. [[1]](diffhunk://#diff-e14c6c1119e1a8b095bac5f2c1015beafb1c1926f41803f3c8e3691eb11bbf72R5-R21) [[2]](diffhunk://#diff-ac25b49e75a4d28aa37ad68e4360f00a6c43d015ab2e244d37ee2e966d0039e4R33-R56) [[3]](diffhunk://#diff-6f6ef3067810563bd09e3ba03c3eca318d042d81f291e42dabf66c10c0e723c7R7-R137)
* Added `OTLP_STDOUT_SPAN_EXPORTER_LOG_LEVEL` and …
=> release: python/otlp-stdout-span-exporter v0.13.0

packages/rust/lambda-otel-lite/CHANGELOG.md, packages/rust/lambda-otel-lite/Cargo.toml, packages/rust/lambda-otel-lite/src/propagation.rs, packages/rust/lambda-otel-lite/src/telemetry.rs
This pull request introduces a patch release (`0.13.1`) for the `lambda-otel-lite` package, focusing on improving X-Ray propagation, context extraction, and sampling logic. Key changes include enhancements to the propagator registration order, better handling of sampled traces, and improved environment variable usage. Below are the most important changes grouped by theme:
* Adjusted the propagator registration order to prioritize W3C TraceContext over AWS X-Ray, ensuring the last valid context wins during extraction (`src/telemetry.rs`).
* Enhanced X-Ray propagation logic to skip context extraction for `Sampled=0` in `_X_AMZN_TRACE_ID`, allowing root span sampling when X-Ray is disabled (`src/propagation.rs`).
* Added checks to ensure only valid and sampled contexts are extracted from …
=> release: rust/lambda-otel-lite v0.13.1

Cargo.toml, packages/rust/otlp-stdout-span-exporter/CHANGELOG.md, packages/rust/otlp-stdout-span-exporter/Cargo.toml, packages/rust/otlp-stdout-span-exporter/examples/README.md, packages/rust/otlp-stdout-span-exporter/examples/simple-pipe-hello.rs, packages/rust/otlp-stdout-span-exporter/src/lib.rs
This pull request updates the `otlp-stdout-span-exporter` crate to version 0.14.0 with significant changes, including dependency upgrades, new examples, and code refactoring for improved maintainability and compatibility with OpenTelemetry SDK 0.29.0. Below are the most important changes grouped by theme:
* Upgraded OpenTelemetry dependencies from 0.28.0 to 0.29.0 and updated the API implementation to address breaking changes and deprecations introduced in the new version. (`packages/rust/otlp-stdout-span-exporter/CHANGELOG.md`, `Cargo.toml`) [[1]](diffhunk://#diff-51c986c5bb8e2e0e9f9c5ecc6f5ac74d2f94a63485f77b241081dc12820081ffR8-R15) [[2]](diffhunk://#diff-139d37c5c8f0270080968f69d2217b6dc710f974739d4ef4f2b7410ce95f9ee6L3-R3)
* Added the `nix` dependency with version 0.29.0 and `fs` …
=> release: rust/otlp-stdout-span-exporter v0.14.0

Cargo.toml, packages/rust/lambda-otel-lite/CHANGELOG.md, packages/rust/lambda-otel-lite/Cargo.toml, packages/rust/lambda-otel-lite/PUBLISHING.md, packages/rust/lambda-otel-lite/README.md, packages/rust/lambda-otel-lite/examples/handler/main.rs, packages/rust/lambda-otel-lite/examples/samconfig.toml, packages/rust/lambda-otel-lite/examples/template.yaml, packages/rust/lambda-otel-lite/examples/tower/main.rs, packages/rust/lambda-otel-lite/src/extension.rs, packages/rust/lambda-otel-lite/src/handler.rs, packages/rust/lambda-otel-lite/src/layer.rs, packages/rust/lambda-otel-lite/src/processor.rs, packages/rust/lambda-otel-lite/src/telemetry.rs
This pull request introduces updates to dependencies, improves the logging system, and refactors the codebase for better maintainability and performance in the `lambda-otel-lite` project. Key changes include upgrading dependency versions, replacing `BoxFuture` with more efficient return types for futures, and enhancing logging with structured events. Below is a categorized summary of the most important changes:
* Updated `reqwest-tracing` to version `0.5.7` with support for `opentelemetry_0_29`.
* Upgraded `aws-sdk-secretsmanager` and `aws-sdk-cloudwatchlogs` to version `1` for consistency with other AWS SDK dependencies.
* Updated `otlp-stdout-span-exporter` to version `0.14.0` in `Cargo.toml` and adjusted the version in the publishing checklist. …
=> release: rust/lambda-otel-lite v0.14.0

Cargo.toml, packages/rust/otlp-stdout-span-exporter/CHANGELOG.md, packages/rust/otlp-stdout-span-exporter/Cargo.toml, packages/rust/otlp-stdout-span-exporter/src/lib.rs
This pull request introduces version `0.15.0` of the `otlp-stdout-span-exporter` package, with significant updates to enhance functionality, improve testing, and clean up dependencies. The changes include new features for the `Output` trait, a new `BufferOutput` struct for testing, and updates to dependency management.
* Made the `Output` trait public and added `is_pipe()` and `touch_pipe()` methods to support named pipe operations. These methods enable checking if the output is a named pipe and performing a "touch" operation to generate EOF signals for downstream readers. (`[[1]](diffhunk://#diff-5e5a6c2c01507f300be15a04a7ce487666ff70869d5bffba3cd94bd4a1973040L204-R204)`, `[[2]](diffhunk://#diff-5e5a6c2c01507f300be15a04a7ce487666ff70869d5bffba3cd94bd4a1973040R215-R235)`, …
=> release: rust/otlp-stdout-span-exporter v0.15.0

packages/python/otlp-stdout-span-exporter/CHANGELOG.md, packages/python/otlp-stdout-span-exporter/pyproject.toml, packages/python/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter/exporter.py, packages/python/otlp-stdout-span-exporter/tests/test_otlp_stdout_span_exporter.py
This pull request introduces version 0.15.0 of the `otlp-stdout-span-exporter` package, adding new functionality for handling empty span batches, fixing edge cases with named pipes, and updating tests to ensure robust coverage. The most significant changes include enhancements to the `export` method, updates to the test suite, and a version bump.
* Added logic to detect empty span batches and generate EOF signals for named pipes, including a "pipe touch" operation to open and close the pipe immediately when no spans are present. This prevents downstream extensions from hanging.
* Introduced a `mock_span` fixture to standardize tests with non-empty span lists, ensuring consistent behavior across various test cases.
* Updated multiple test cases to use the `mock_span` fixture and validated …
=> release: python/otlp-stdout-span-exporter v0.15.0

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/package.json, packages/node/otlp-stdout-span-exporter/src/__tests__/otlp_stdout_span_exporter.test.ts, packages/node/otlp-stdout-span-exporter/src/otlp_stdout_span_exporter.ts
This pull request introduces several updates to the `@dev7a/otlp-stdout-span-exporter` package, including new features, dependency updates, and expanded test coverage. The most significant changes involve adding support for EOF signals on named pipes, improving test robustness with mock spans, and handling edge cases for empty span exports.
* Added support for generating EOF signals on named pipes when exporting empty span batches. Implemented a "pipe touch" operation to open and close the pipe immediately when export is called with empty spans.
* Updated `@opentelemetry/otlp-transformer` to version `^0.57.2` and `@opentelemetry/sdk-trace-base` to version `^1.30.1` in `package.json`.
* Introduced a `createMockSpan` helper function to improve test coverage and ensure non-empty spans are …
=> release: node/otlp-stdout-span-exporter v0.15.0

packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/README.md, packages/node/lambda-otel-lite/__tests__/test_processor.ts, packages/node/lambda-otel-lite/__tests__/test_resource.ts, packages/node/lambda-otel-lite/examples/template.yaml, packages/node/lambda-otel-lite/package-lock.json, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/constants.ts, packages/node/lambda-otel-lite/src/internal/telemetry/init.ts, packages/node/lambda-otel-lite/src/internal/telemetry/processor.ts, packages/node/lambda-otel-lite/src/internal/telemetry/resource.ts
This pull request introduces significant updates to the `@dev7a/lambda-otel-lite` package, focusing on simplifying the span processing logic, removing unused configuration options, and improving test coverage. The most notable changes include removing batch processing logic, updating dependencies, and modifying tests to align with the new behavior.
* Removed batching logic from `LambdaSpanProcessor`—spans are now exported in a single batch regardless of size, and the `forceFlush` method always calls the exporter's `export` method, even when the span buffer is empty. (`packages/node/lambda-otel-lite/src/internal/telemetry/processor.ts`, [[1]](diffhunk://#diff-485c81f552d648e9494fc693b1832bc2034279aaf85daac21693d2c5cc164877L189-R181) …
=> release: node/lambda-otel-lite v0.15.0

cli/startled/CHANGELOG.md, cli/startled/Cargo.toml, cli/startled/RELEASE_NOTES.md, cli/startled/src/benchmark.rs, cli/startled/src/report.rs, cli/startled/src/stats.rs, cli/startled/src/types.rs
This pull request introduces several updates to the `startled` CLI tool, including a version bump, dependency additions, and a comprehensive suite of new tests for benchmarking and reporting functionality.
* Updated the `startled` package version from `0.1.0` to `0.1.1` in `Cargo.toml`.
* Added `tempfile` as a development dependency for temporary file management in tests.
* Added a new test module in `cli/startled/src/benchmark.rs` to validate `FunctionBenchmarkConfig` creation and the `save_report` function's behavior, including cases for default memory configurations and successful report saving.
* Introduced a test module in `cli/startled/src/report.rs` for various utility functions:
- `snake_to_kebab` conversion.
- `calculate_base_path` logic with and without a base URL.
- Data …
=> release cli/startled-v0.1.1

cli/startled/CHANGELOG.md, cli/startled/Cargo.toml, cli/startled/PUBLISHING.md, cli/startled/README.md, cli/startled/RELEASE_NOTES.md, cli/startled/src/benchmark.rs, cli/startled/src/lambda.rs, cli/startled/src/main.rs, cli/startled/src/report.rs, cli/startled/src/templates/css/style.css, cli/startled/src/types.rs, cli/startled/testbed/functions/rust/stdout/src/main.rs
This pull request introduces significant updates to the `startled` CLI, including new features, required argument changes, improved output handling, and internal code refactoring. The changes enhance the benchmarking capabilities, simplify configurations, and improve the user experience, particularly for parallel benchmarking scenarios.
* Added a `--parallel` option to the `stack` command, enabling concurrent benchmarking of multiple Lambda functions. This feature includes an overall progress bar, a final summary output, and suppressed detailed logs for individual benchmarks. (`cli/startled/CHANGELOG.md`, `cli/startled/README.md`, `cli/startled/RELEASE_NOTES.md`, [[1]](diffhunk://#diff-c5590841151d74f9edd27ee7308b1b096f2ef5614a42a5113ece9a74e69d3e55L163-R169) …
=> release: cli/startled v0.3.0

cli/livetrace/CHANGELOG.md, cli/livetrace/Cargo.toml, cli/livetrace/README.md, cli/livetrace/RELEASE_NOTES.md, cli/livetrace/src/aws_setup.rs, cli/livetrace/src/cli.rs, cli/livetrace/src/config.rs, cli/livetrace/src/console_display.rs, cli/livetrace/src/lib.rs, cli/livetrace/src/live_tail_adapter.rs, cli/livetrace/src/poller.rs, cli/livetrace/src/processing.rs
This pull request introduces version `0.2.0` of the `livetrace` CLI tool, bringing significant new features, usability enhancements, bug fixes, and code refactoring. Key highlights include new CLI options for filtering and log fetching, improved color palettes, better handling of defaults in configuration, and modularized code for maintainability. The documentation has also been updated to reflect these changes.
* **CLI Options**: Added `--grep <REGEX>` for filtering spans/events using regex with highlighted matches, and `--backtrace <DURATION>` for fetching logs from a specified duration ago in polling mode. Duration-based arguments now support units like `s`, `m`, `h`. [[1]](diffhunk://#diff-c451b7e6fddedec09135853b8dcba814a2a3f6235787c31db7de9b2549b95f4bR8-R37) …
=> release cli/livetrace/v0.2.0

cli/livetrace/CHANGELOG.md, cli/livetrace/Cargo.toml, cli/livetrace/README.md, cli/livetrace/RELEASE_NOTES.md
This pull request updates the `livetrace` CLI tool to version `0.2.1`, introduces a new screenshot in the documentation, and provides corresponding updates to metadata and release notes.
* Updated the `livetrace` version from `0.2.0` to `0.2.1` in `Cargo.toml` to reflect the new release.
* Added a new screenshot of the `livetrace` CLI in action to the `README.md` file to improve user understanding of the tool.
* Removed a duplicate screenshot from the `Overview` section of the `README.md` for better clarity.
* Updated `CHANGELOG.md` to include details about the `0.2.1` release, including the updated version and documentation changes.
* Added release notes for version `0.2.1` in `RELEASE_NOTES.md`, highlighting the inclusion of the new screenshot.
=> release cli/livetrace v0.2.1

packages/python/otlp-stdout-span-exporter/CHANGELOG.md, packages/python/otlp-stdout-span-exporter/pyproject.toml
This pull request updates the `otlp-stdout-span-exporter` package to version 0.16.0, introducing new features, upgrading dependencies, and adding entry points for OpenTelemetry auto-discovery. Below are the most significant changes:
* Updated the package version from `0.15.0` to `0.16.0` in `pyproject.toml`.
* Upgraded development dependencies in `pyproject.toml`:
- `pytest` to `>=8.4.0` (from `>=7.4.0`).
- `pytest-asyncio` to `>=1.0.0` (from `>=0.21.0`).
- `pytest-cov` to `>=6.2.1` (from `>=4.1.0`).
- `ruff` to `>=0.9.6` (from `>=0.1.0`).
- `mypy` to `>=1.15.0` (from `>=1.7.0`).
* Added entry points for OpenTelemetry auto-discovery in `pyproject.toml`:
- Defined `otlpstdout` entry point under `opentelemetry_traces_exporter`.
* Updated `CHANGELOG.md` to reflect changes in version 0.16.0, …
=> release: python/otlp-stdout-span-exporter v0.16.0

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/README.md, packages/node/otlp-stdout-span-exporter/package-lock.json, packages/node/otlp-stdout-span-exporter/package.json
This pull request updates the `otlp-stdout-span-exporter` package to version 0.16.0, introducing breaking changes due to dependency upgrades and aligning with OpenTelemetry SDK 2.x requirements. It also updates the minimum Node.js version and adjusts package metadata accordingly.
* **Changelog (`CHANGELOG.md`)**: Documented the upgrade to OpenTelemetry dependencies (2.x versions) and updated the minimum Node.js version requirement to `^18.19.0 || >=20.6.0`. Migration notes provided for compatibility guidance.
* **Package metadata (`package.json` and `package-lock.json`)**: Updated dependencies to OpenTelemetry SDK 2.x versions (`@opentelemetry/core`, `@opentelemetry/sdk-trace-base`, `@opentelemetry/otlp-transformer`, etc.) and adjusted Node.js version requirements. …
=> release: node/otlp-stdout-span-exporter v0.16.0

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/README.md, packages/node/otlp-stdout-span-exporter/package-lock.json, packages/node/otlp-stdout-span-exporter/package.json, packages/node/otlp-stdout-span-exporter/scripts/build-esm-wrapper.js
This pull request updates the `otlp-stdout-span-exporter` package to version 0.17.0, introducing ESM support, modifying dependency management, and aligning with OpenTelemetry SDK 2.x. The changes ensure compatibility with both CommonJS and ES Modules while improving version management by transitioning OpenTelemetry packages to peer dependencies.
* Added ESM (ES Modules) support via a lightweight wrapper (~400 bytes). The package now supports both CommonJS (`require`) and ESM (`import`) syntax. [[1]](diffhunk://#diff-98d7656b1775668a361eb259643823fb60356e4f05cc19ce00f0d804403e6012R8-R18) [[2]](diffhunk://#diff-d2345cbdfe13c980dc77f7ca9215ac6695f0dfa58951f16698e00bf324e0c752R47-R79)
* **BREAKING**: OpenTelemetry packages moved from `dependencies` to `peerDependencies` for better version …
=> release: node/otlp-stdout-span-exporter v0.17.0

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/README.md, packages/node/otlp-stdout-span-exporter/package.json
This pull request updates the `@dev7a/otlp-stdout-span-exporter` package to version `0.17.1`, addressing bundling compatibility issues and improving the handling of ESM and CommonJS exports. The changes ensure better support for both native Node.js environments and bundlers like webpack.
* [`packages/node/otlp-stdout-span-exporter/package.json`](diffhunk://#diff-de9bcc5499221be2efd6fb53ecc3d3967208154d47830f6f69e94693d1ffafbeL3-R13): Updated the `exports` field to include a Node.js-specific condition, ensuring that the ESM wrapper is used only in native Node.js environments while bundlers default to the CommonJS version.
* [`packages/node/otlp-stdout-span-exporter/CHANGELOG.md`](diffhunk://#diff-98d7656b1775668a361eb259643823fb60356e4f05cc19ce00f0d804403e6012R8-R14): Added a changelog …
=> release: node/otlp-stdout-span-exporter v0.17.1

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/README.md, packages/node/otlp-stdout-span-exporter/package.json, packages/node/otlp-stdout-span-exporter/scripts/build-esm-wrapper.js
This pull request introduces changes to address webpack bundling issues and improve compatibility for the `@dev7a/otlp-stdout-span-exporter` package. The main updates include modifying the export strategy, adding experimental ESM support via a subpath, and enhancing error handling in the ESM wrapper. Below is a breakdown of the most important changes.
* **Changelog Update**: Documented changes in `packages/node/otlp-stdout-span-exporter/CHANGELOG.md` to reflect the new version `0.17.2`, highlighting fixes for webpack bundling issues and the introduction of ESM support via the `/esm` subpath.
* **README Update**: Updated `packages/node/otlp-stdout-span-exporter/README.md` to clarify that ESM support is now experimental and available via a subpath, with warnings about incompatibility with …
=> release: node/otlp-stdout-span-exporter v0.17.2

packages/node/otlp-stdout-span-exporter/CHANGELOG.md, packages/node/otlp-stdout-span-exporter/README.md, packages/node/otlp-stdout-span-exporter/package.json
This pull request addresses a critical issue with the ESM support in the `@dev7a/otlp-stdout-span-exporter` package. The changes ensure that the `/esm` subpath export works correctly in the published npm package by integrating the ESM wrapper into the main build process. Additionally, the documentation and versioning have been updated to reflect these fixes.
* [`packages/node/otlp-stdout-span-exporter/package.json`](diffhunk://#diff-de9bcc5499221be2efd6fb53ecc3d3967208154d47830f6f69e94693d1ffafbeL24-R24): Updated the `build` script to include `build-esm-wrapper`, ensuring the `/esm` subpath export functions correctly in the published package.
* [`packages/node/otlp-stdout-span-exporter/CHANGELOG.md`](diffhunk://#diff-98d7656b1775668a361eb259643823fb60356e4f05cc19ce00f0d804403e6012R8-R13): …
=> release: node/otlp-stdout-span-exporter v0.17.3

packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/extension/index.ts
This pull request addresses a critical timeout issue in the Lambda Extensions API and introduces improvements to HTTP request handling. The changes ensure more robust behavior for long-polling and admin operations, enhance error handling, and update the package version to reflect these fixes.
* **Critical Fix**: Resolved timeout issue in Lambda Extensions API long-polling, preventing "HTTP request timeout" errors for extensions.
* Updated `syncHttpRequest` function to make HTTP timeout optional, allowing long-polling requests to proceed without timeouts while retaining a 5-second timeout for admin operations. [[1]](diffhunk://#diff-8f5fbf11d191e06c65ad7e26891eeb134e3b5998679d1695a54f8620b072148aR34-R45) [[2]](diffhunk://#diff-8f5fbf11d191e06c65ad7e26891eeb134e3b5998679d1695a54f8620b072148a …
=> release: node/lambda-otel-lite v0.16.1

packages/node/lambda-otel-lite/CHANGELOG.md, packages/node/lambda-otel-lite/__tests__/test_processor.ts, packages/node/lambda-otel-lite/package.json, packages/node/lambda-otel-lite/src/internal/telemetry/processor.ts
This pull request addresses a critical issue in the `LambdaSpanProcessor` related to the shutdown process, ensuring that spans are properly flushed before marking the processor as shutdown. It also updates the package version and corresponding tests to reflect this fix.
* [`packages/node/lambda-otel-lite/src/internal/telemetry/processor.ts`](diffhunk://#diff-485c81f552d648e9494fc693b1832bc2034279aaf85daac21693d2c5cc164877L244-R245): Adjusted the shutdown order to call `forceFlush()` before setting the `isShutdown` flag, preventing data loss during Lambda function termination.
* [`packages/node/lambda-otel-lite/__tests__/test_processor.ts`](diffhunk://#diff-96baf5cd6e4355a9c5e628c8e16989aab85a1dcd445f3d86eeec55021ddf4adfL69-R77): Updated tests to verify that buffered spans are exported …
=> release: node/lambda-otel-lite v0.16.2

Cargo.lock, cli/startled/CHANGELOG.md, cli/startled/Cargo.toml, cli/startled/README.md, cli/startled/RELEASE_NOTES.md, cli/startled/src/main.rs, cli/startled/src/report.rs, cli/startled/src/templates/index.html
This pull request introduces version `0.4.0` of the `startled` CLI tool, focusing on enhancing the `report` command with new customization options and improving the landing page UI. The changes include updates to the command-line interface, internal functionality, and documentation to support these new features.
**CLI Customization Options:**
- Added `--title` option to set a custom title for the report landing page. [[1]](diffhunk://#diff-5fb52f72c3daaba5adfbdfaddaf0e2bc6b28ebbb5e4d9e8a4082eaf66b5d8886R152-R159) [[2]](diffhunk://#diff-5fb52f72c3daaba5adfbdfaddaf0e2bc6b28ebbb5e4d9e8a4082eaf66b5d8886R329-R330) [[3]](diffhunk://#diff-cf5a77c542971afe74e9afa350d67cb8676c3402f54374bad52106535c17f550R303) [[4]](diffhunk://#diff-aff33bf4e337463eb1a6180a9b58b944752069b10f5ca6a932555ac84afe0573R25 …
=> release: cli/startled v0.4.0

Cargo.lock, cli/startled/CHANGELOG.md, cli/startled/Cargo.toml, cli/startled/RELEASE_NOTES.md, cli/startled/src/report.rs
Fix: JavaScript file embedding issue for distributed binaries
- Fixed 'Failed to copy default lib.js' error in GitHub releases
- Changed from env!(CARGO_MANIFEST_DIR) to include_str!() for JS embedding
- Ensures report command works in all deployment scenarios
=> release: cli/startled v0.4.1

cli/startled/CHANGELOG.md, cli/startled/Cargo.toml, cli/startled/README.md, cli/startled/RELEASE_NOTES.md, cli/startled/src/main.rs, cli/startled/src/report.rs
This pull request introduces a new feature to the `startled` CLI tool, allowing users to specify custom file extensions for generated reports using the `--suffix` option. This enhancement improves flexibility in report generation and integrates seamlessly with custom templates. Additionally, telemetry initialization has been refined to optimize performance by limiting it to commands requiring AWS access.
* Added `--suffix` option to the `report` command, enabling users to customize the file extension for generated reports (default: `.html`). This supports formats like `.md`, `.txt`, and `.json when used with custom templates. (`cli/startled/src/main.rs` - [[1]](diffhunk://#diff-5fb52f72c3daaba5adfbdfaddaf0e2bc6b28ebbb5e4d9e8a4082eaf66b5d8886R160-R163) …
=> release: cli/startled v0.5.1

.github/workflows/publish-rust-serverless-otlp-forwarder-core.yml, packages/rust/serverless-otlp-forwarder-core/CHANGELOG.md, packages/rust/serverless-otlp-forwarder-core/Cargo.toml, packages/rust/serverless-otlp-forwarder-core/PUBLISHING.md, packages/rust/serverless-otlp-forwarder-core/README.md, packages/rust/serverless-otlp-forwarder-core/src/core_parser.rs, packages/rust/serverless-otlp-forwarder-core/src/http_sender.rs, packages/rust/serverless-otlp-forwarder-core/src/lib.rs, packages/rust/serverless-otlp-forwarder-core/src/processor.rs, packages/rust/serverless-otlp-forwarder-core/src/span_compactor.rs, packages/rust/serverless-otlp-forwarder-core/src/telemetry.rs
This pull request introduces the `serverless-otlp-forwarder-core` Rust package, along with its associated CI/CD workflow, metadata, and documentation. The changes establish a foundation for publishing, testing, and maintaining the package, which is designed to facilitate serverless telemetry forwarding on AWS Lambda. Key updates include the addition of a GitHub Actions workflow for automated testing and publishing, comprehensive package metadata, and a publishing checklist.
- [`.github/workflows/publish-rust-serverless-otlp-forwarder-core.yml`](diffhunk://#diff-852742a4526c647e85682b6bf3953a3ffd9d8ca23c4e7791bf1f12e0f2f46c21R1-R111): Added a GitHub Actions workflow to automate testing, quality checks, and publishing of the `serverless-otlp-forwarder-core` crate. Includes …
=> release: rust/serverless-otlp-forwarder-core v0.1.0
